NumPy- Numerical Python

Advantages of Numpy Arrays:

      1. Allows several mathematics Operations
      2.Faster Operations

In [1]:
import numpy as np

list vs numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list =[i for  i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007015350000010301


In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)




0.00017385399999980677


Numpy Arrays

In [9]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
a.shape

(4,)

In [15]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
b.shape

(2, 4)

In [17]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype= float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays

In [18]:
# create a numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#creating a numpy arrays of ones

y = np.ones((2,2))
print(y)

[[1. 1.]
 [1. 1.]]


In [20]:
#arrays of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
#create a identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.16068896 0.1977785  0.20672123 0.65659166]
 [0.94590975 0.74272947 0.25420466 0.24859196]
 [0.24130968 0.38023972 0.92251767 0.1088864 ]]


In [24]:
#random  integers values array with in specific range

c = np.random.randint(10,100,(3,4))
print(c)

[[55 85 88 47]
 [22 72 85 45]
 [21 69 19 14]]


In [26]:
#array of evenly spaced values -->specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [28]:
# array of evenly spaced values --> specifying the step
d = np.arange(10,30,5)
print(d)

[10 15 20 25]


In [30]:
# converty a list to a numpy array
list2 = [10,20,30,40,50]

np_array = np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [31]:
c =np.random.randint(10,90,(5,5))
print(c)

[[23 44 51 19 86]
 [38 21 39 54 59]
 [46 34 73 81 29]
 [60 76 35 11 45]
 [64 46 49 45 44]]


In [32]:
#array dimension
print(c.shape)

(5, 5)


In [33]:
#number of dimensions
print(c.ndim)

2


In [34]:
# checking a number of elements in an array
print(c.size)

25


In [35]:
# checking a data type of values in the array
print(c.dtype)

int64


mathematical operations on a np array

In [36]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9]

print(list1 + list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [41]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))



In [42]:
print(a)
print(b)

[[9 3 6]
 [8 3 0]
 [2 9 7]]
[[16 15 19]
 [16 16 12]
 [10 10 12]]


In [44]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 18 25]
 [24 19 12]
 [12 19 19]]
[[ -7 -12 -13]
 [ -8 -13 -12]
 [ -8  -1  -5]]
[[144  45 114]
 [128  48   0]
 [ 20  90  84]]
[[0.5625     0.2        0.31578947]
 [0.5        0.1875     0.        ]
 [0.2        0.9        0.58333333]]


In [45]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [46]:
print(a)
print(b)

[[0 9 5]
 [6 9 2]
 [8 7 1]]
[[15 11 14]
 [16 12 15]
 [15 17 14]]


In [47]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 20 19]
 [22 21 17]
 [23 24 15]]
[[-15  -2  -9]
 [-10  -3 -13]
 [ -7 -10 -13]]
[[  0  99  70]
 [ 96 108  30]
 [120 119  14]]
[[0.         0.81818182 0.35714286]
 [0.375      0.75       0.13333333]
 [0.53333333 0.41176471 0.07142857]]


Array manipulation

In [48]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 3]
 [6 6 7]]
(2, 3)


In [49]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 6]
 [9 6]
 [3 7]]
(3, 2)


In [50]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 7 5]
 [2 9 7]]
(2, 3)


In [51]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 7]
 [5 2]
 [9 7]]
(3, 2)
